// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package database

import (
	"github.com/google/uuid"
)

type Note struct {
	ID      uuid.UUID
	Name    string
	Content string
	UserID  uuid.UUID
}

type User struct {
	ID           uuid.UUID
	Login        string
	Password     string
	RefreshToken string
}
